BEGIN

-- Table: "T_ASSET_ARCHITECTURE_ASA"

-- DROP TABLE "T_ASSET_ARCHITECTURE_ASA";

CREATE TABLE "T_ASSET_ARCHITECTURE_ASA"
(
  "ASA_ID" serial NOT NULL,
  version integer NOT NULL,
  "ASA_NAME" text NOT NULL,
  "ASA_DELETE" timestamp without time zone,
  CONSTRAINT "T_ASSET_ARCHITECTURE_ASA_pkey" PRIMARY KEY ("ASA_ID" )
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "T_ASSET_ARCHITECTURE_ASA"
  OWNER TO echoes;


-- Table: "T_ASSET_DISTRIBUTION_ASD"

-- DROP TABLE "T_ASSET_DISTRIBUTION_ASD";

CREATE TABLE "T_ASSET_DISTRIBUTION_ASD"
(
  "ASD_ID" serial NOT NULL,
  version integer NOT NULL,
  "ASD_NAME" text NOT NULL,
  "ASD_DELETE" timestamp without time zone,
  CONSTRAINT "T_ASSET_DISTRIBUTION_ASD_pkey" PRIMARY KEY ("ASD_ID" )
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "T_ASSET_DISTRIBUTION_ASD"
  OWNER TO echoes;

  -- Table: "T_ASSET_RELEASE_ASR"

-- DROP TABLE "T_ASSET_RELEASE_ASR";

CREATE TABLE "T_ASSET_RELEASE_ASR"
(
  "ASR_ID" serial NOT NULL,
  version integer NOT NULL,
  "ASR_NAME" text NOT NULL,
  "ASR_DELETE" timestamp without time zone,
  CONSTRAINT "T_ASSET_RELEASE_ASR_pkey" PRIMARY KEY ("ASR_ID" )
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "T_ASSET_RELEASE_ASR"
  OWNER TO echoes;

-- Table: "T_PROBE_PACKAGE_PPA"

-- DROP TABLE "T_PROBE_PACKAGE_PPA";

CREATE TABLE "T_PROBE_PACKAGE_PPA"
(
  "PPA_ID" serial NOT NULL,
  version integer NOT NULL,
  "PPA_FILENAME" text NOT NULL,
  "PPA_DELETE" timestamp without time zone,
  CONSTRAINT "T_PROBE_PACKAGE_PPA_pkey" PRIMARY KEY ("PPA_ID" )
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "T_PROBE_PACKAGE_PPA"
  OWNER TO echoes;

  -- Table: "T_PROBE_PACKAGE_PARAMETER_PPP"

-- DROP TABLE "T_PROBE_PACKAGE_PARAMETER_PPP";

CREATE TABLE "T_PROBE_PACKAGE_PARAMETER_PPP"
(
  "PPP_ID" serial NOT NULL,
  version integer NOT NULL,
  "PPP_PACKAGE_VERSION" text NOT NULL,
  "PPP_PROBE_VERSION" text NOT NULL,
  "PPP_DELETE" timestamp without time zone,
  "PPP_ASA_ASA_ID" bigint,
  "PPP_ASD_ASD_ID" bigint,
  "PPP_ASR_ASR_ID" bigint,
  "PPP_PPA_PPA_ID" bigint,
  CONSTRAINT "T_PROBE_PACKAGE_PARAMETER_PPP_pkey" PRIMARY KEY ("PPP_ID" ),
  CONSTRAINT "fk_T_PROBE_PACKAGE_PARAMETER_PPP_PPP_ASA" FOREIGN KEY ("PPP_ASA_ASA_ID")
      REFERENCES "T_ASSET_ARCHITECTURE_ASA" ("ASA_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_T_PROBE_PACKAGE_PARAMETER_PPP_PPP_ASD" FOREIGN KEY ("PPP_ASD_ASD_ID")
      REFERENCES "T_ASSET_DISTRIBUTION_ASD" ("ASD_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_T_PROBE_PACKAGE_PARAMETER_PPP_PPP_ASR" FOREIGN KEY ("PPP_ASR_ASR_ID")
      REFERENCES "T_ASSET_RELEASE_ASR" ("ASR_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_T_PROBE_PACKAGE_PARAMETER_PPP_PPP_PPA" FOREIGN KEY ("PPP_PPA_PPA_ID")
      REFERENCES "T_PROBE_PACKAGE_PPA" ("PPA_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "T_PROBE_PACKAGE_PARAMETER_PPP"
  OWNER TO echoes;



ALTER TABLE "T_ASSET_AST" ADD COLUMN "AST_ASA_ASA_ID" bigint;
ALTER TABLE "T_ASSET_AST" ADD CONSTRAINT "fk_T_ASSET_AST_AST_ASA" FOREIGN KEY ("AST_ASA_ASA_ID")
      REFERENCES "T_ASSET_ARCHITECTURE_ASA" ("ASA_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "T_ASSET_AST" ADD COLUMN "AST_ASD_ASD_ID" bigint;
ALTER TABLE "T_ASSET_AST" ADD CONSTRAINT "fk_T_ASSET_AST_AST_ASD" FOREIGN KEY ("AST_ASD_ASD_ID")
      REFERENCES "T_ASSET_DISTRIBUTION_ASD" ("ASD_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "T_ASSET_AST" ADD COLUMN "AST_ASR_ASR_ID" bigint;
ALTER TABLE "T_ASSET_AST" ADD CONSTRAINT "fk_T_ASSET_AST_AST_ASR" FOREIGN KEY ("AST_ASR_ASR_ID")
      REFERENCES "T_ASSET_RELEASE_ASR" ("ASR_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "T_ASSET_AST"
DROP IF EXISTS "AST_ARCHITECTURE";

ALTER TABLE "T_ASSET_AST"
DROP IF EXISTS "AST_DISTRIB_NAME";

ALTER TABLE "T_ASSET_AST"
DROP IF EXISTS "AST_DISTRIB_RELEASE";

END
