ALTER TABLE "T_PROBE_PRB"
ADD "PRB_PPP_PPP_ID" bigint;

ALTER TABLE "T_PROBE_PRB"
ADD CONSTRAINT "fk_T_PROBE_PRB_PRB_PPP" FOREIGN KEY ("PRB_PPP_PPP_ID")
      REFERENCES "T_PROBE_PACKAGE_PARAMETER_PPP" ("PPP_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;
