BEGIN

ALTER TABLE "T_ASSET_AST" ADD COLUMN "AST_ORG_ORG_ID" bigint;
ALTER TABLE "T_ASSET_AST" ADD CONSTRAINT "fk_T_ASSET_AST_AST_ORG" FOREIGN KEY ("AST_ORG_ORG_ID")
      REFERENCES "T_ORGANIZATION_ORG" ("ORG_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

UPDATE "T_ASSET_AST" SET "AST_ORG_ORG_ID" = (SELECT "PRB_ORG_ORG_ID" FROM "T_PROBE_PRB" WHERE "PRB_ID" = "AST_PRB_PRB_ID");

END
