-- Table: "TJ_ADO_STY"

-- DROP TABLE "TJ_ADO_STY";

CREATE TABLE "TJ_ADO_STY"
(
  "T_ADDON_ADO_ADO_ID" bigint NOT NULL,
  "T_SEARCH_TYPE_STY_STY_ID" bigint NOT NULL,
  CONSTRAINT "TJ_ADO_STY_pkey" PRIMARY KEY ("T_ADDON_ADO_ADO_ID" , "T_SEARCH_TYPE_STY_STY_ID" ),
  CONSTRAINT "fk_TJ_ADO_STY_key1" FOREIGN KEY ("T_ADDON_ADO_ADO_ID")
      REFERENCES "T_ADDON_ADO" ("ADO_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_TJ_ADO_STY_key2" FOREIGN KEY ("T_SEARCH_TYPE_STY_STY_ID")
      REFERENCES "T_SEARCH_TYPE_STY" ("STY_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "TJ_ADO_STY"
  OWNER TO echoes;

-- Index: "TJ_ADO_STY_T_ADDON_ADO"

-- DROP INDEX "TJ_ADO_STY_T_ADDON_ADO";

CREATE INDEX "TJ_ADO_STY_T_ADDON_ADO"
  ON "TJ_ADO_STY"
  USING btree
  ("T_ADDON_ADO_ADO_ID" );

-- Index: "TJ_ADO_STY_T_SEARCH_TYPE_STY"

-- DROP INDEX "TJ_ADO_STY_T_SEARCH_TYPE_STY";

CREATE INDEX "TJ_ADO_STY_T_SEARCH_TYPE_STY"
  ON "TJ_ADO_STY"
  USING btree
  ("T_SEARCH_TYPE_STY_STY_ID" );

