ALTER TABLE "T_ALERT_VALUE_AVA" ADD COLUMN "AVA_AST_AST_ID" bigint;
ALTER TABLE "T_ALERT_VALUE_AVA" ADD CONSTRAINT "fk_T_ALERT_VALUE_AVA_AVA_AST" FOREIGN KEY ("AVA_AST_AST_ID")
      REFERENCES "T_ASSET_AST" ("AST_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

UPDATE "T_ALERT_VALUE_AVA" SET "AVA_AST_AST_ID" = "TJ_AST_ALE"."T_ASSET_AST_AST_ID" FROM "T_ALERT_ALE", "TJ_AST_ALE" WHERE "T_ALERT_ALE"."ALE_AVA_AVA_ID" = "T_ALERT_VALUE_AVA"."AVA_ID" AND "T_ALERT_ALE"."ALE_ID" = "TJ_AST_ALE"."T_ALERT_ALE_ALE_ID";

DROP TABLE "TJ_ALE_AST";

ALTER TABLE "T_INFORMATION_INF" ADD COLUMN "INF_DESC" text;
