ALTER TABLE "T_SEARCH_SEA"
	DROP COLUMN "SEA_PERIOD";
ALTER TABLE "T_SEARCH_SEA"
	ADD COLUMN "SEA_PERIOD" int;
UPDATE "T_SEARCH_SEA" SET "SEA_PERIOD" = 60;
ALTER TABLE "T_SEARCH_SEA"
	ALTER COLUMN "SEA_PERIOD" SET NOT NULL;
