ALTER TABLE "T_ALERT_VALUE_AVA" 
	ALTER COLUMN "SEA_ID" SET DATA TYPE bigint;

ALTER TABLE "T_ALERT_VALUE_AVA" 
	ALTER COLUMN "SRC_ID" SET DATA TYPE bigint;


ALTER TABLE "T_INFORMATION_HISTORICAL_VALUE_IHV" 
	ALTER COLUMN "SEA_ID" SET DATA TYPE bigint;

ALTER TABLE "T_INFORMATION_HISTORICAL_VALUE_IHV" 
	ALTER COLUMN "SRC_ID" SET DATA TYPE bigint;

ALTER TABLE "T_INFORMATION_INF" 
	ALTER COLUMN "SEA_ID" SET DATA TYPE bigint;

ALTER TABLE "T_INFORMATION_INF" 
	ALTER COLUMN "SRC_ID" SET DATA TYPE bigint;

ALTER TABLE "T_INFORMATION_VALUE_IVA" 
	ALTER COLUMN "SEA_ID" SET DATA TYPE bigint;

ALTER TABLE "T_INFORMATION_VALUE_IVA" 
	ALTER COLUMN "SRC_ID" SET DATA TYPE bigint;

ALTER TABLE "T_SEARCH_PARAMETER_VALUE_SEV" 
	ALTER COLUMN "SEA_ID" SET DATA TYPE bigint;

ALTER TABLE "T_SEARCH_PARAMETER_VALUE_SEV" 
	ALTER COLUMN "SRC_ID" SET DATA TYPE bigint;

ALTER TABLE "T_SEARCH_SEA" 
	ALTER COLUMN "SEA_ID" SET DATA TYPE bigint;

ALTER TABLE "T_SEARCH_SEA" 
	ALTER COLUMN "SRC_ID" SET DATA TYPE bigint;

ALTER TABLE "T_SEARCH_UNIT_SEU" 
	ALTER COLUMN "SEA_ID" SET DATA TYPE bigint;

ALTER TABLE "T_SEARCH_UNIT_SEU" 
	ALTER COLUMN "SRC_ID" SET DATA TYPE bigint;

ALTER TABLE "T_SOURCE_PARAMETER_VALUE_SPV" 
	ALTER COLUMN "SRC_ID" SET DATA TYPE bigint;

ALTER TABLE "T_SOURCE_SRC" 
	ALTER COLUMN "SRC_ID" SET DATA TYPE bigint;


