-- Table: "TJ_ENG_ORG"

-- DROP TABLE "TJ_ENG_ORG";

CREATE TABLE "TJ_ENG_ORG"
(
  version integer NOT NULL,
  "ENO_token" text NOT NULL,
  "ENO_DELETE" timestamp without time zone,
  "ENG_ID_ENG_ID" bigint NOT NULL,
  "ORG_ID_ORG_ID" bigint NOT NULL,
  CONSTRAINT "TJ_ENG_ORG_pkey" PRIMARY KEY ("ENG_ID_ENG_ID" , "ORG_ID_ORG_ID" ),
  CONSTRAINT "fk_TJ_ENG_ORG_ENG_ID" FOREIGN KEY ("ENG_ID_ENG_ID")
      REFERENCES "T_ENGINE_ENG" ("ENG_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_TJ_ENG_ORG_ORG_ID" FOREIGN KEY ("ORG_ID_ORG_ID")
      REFERENCES "T_ORGANIZATION_ORG" ("ORG_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "TJ_ENG_ORG"
  OWNER TO echoes;
