ALTER TABLE "T_ALERT_MEDIA_SPECIALIZATION_AMS" ADD COLUMN "AMS_MESSAGE" text;


--
-- TOC entry 222 (class 1259 OID 172323)
-- Dependencies: 6
-- Name: T_ALERT_MESSAGE_ALIAS_ASSET_AAA; Type: TABLE; Schema: public; Owner: echoes; Tablespace: 
--

CREATE TABLE "T_ALERT_MESSAGE_ALIAS_ASSET_AAA" (
    version integer NOT NULL,
    "AAA_ALIAS" text NOT NULL,
    "AAA_DELETE" timestamp without time zone,
    "URO_ID_URO_ID" bigint NOT NULL,
    "AST_ID_AST_ID" bigint NOT NULL,
    "MED_ID_MED_ID" bigint NOT NULL
);


ALTER TABLE public."T_ALERT_MESSAGE_ALIAS_ASSET_AAA" OWNER TO echoes;

--
-- TOC entry 229 (class 1259 OID 172369)
-- Dependencies: 6
-- Name: T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI; Type: TABLE; Schema: public; Owner: echoes; Tablespace: 
--

CREATE TABLE "T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI" (
    version integer NOT NULL,
    "AAI_ALIAS" text NOT NULL,
    "AAI_DELETE" timestamp without time zone,
    "URO_ID_URO_ID" bigint NOT NULL,
    "SEA_ID" bigint NOT NULL,
    "SRC_ID" bigint NOT NULL,
    "PLG_ID_PLG_ID" bigint NOT NULL,
    "INF_VALUE_NUM" integer NOT NULL,
    "INU_ID_INU_ID" bigint NOT NULL,
    "MED_ID_MED_ID" bigint NOT NULL
);


ALTER TABLE public."T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI" OWNER TO echoes;

--
-- TOC entry 230 (class 1259 OID 172377)
-- Dependencies: 6
-- Name: T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC; Type: TABLE; Schema: public; Owner: echoes; Tablespace: 
--

CREATE TABLE "T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC" (
    version integer NOT NULL,
    "AIC_ALIAS" text NOT NULL,
    "AIC_DELETE" timestamp without time zone,
    "URO_ID_URO_ID" bigint NOT NULL,
    "SEA_ID" bigint NOT NULL,
    "SRC_ID" bigint NOT NULL,
    "PLG_ID_PLG_ID" bigint NOT NULL,
    "INF_VALUE_NUM" integer NOT NULL,
    "INU_ID_INU_ID" bigint NOT NULL,
    "ACR_ID_ACR_ID" bigint NOT NULL,
    "MED_ID_MED_ID" bigint NOT NULL
);


ALTER TABLE public."T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC" OWNER TO echoes;

--
-- TOC entry 224 (class 1259 OID 172339)
-- Dependencies: 6
-- Name: T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP; Type: TABLE; Schema: public; Owner: echoes; Tablespace: 
--

CREATE TABLE "T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP" (
    version integer NOT NULL,
    "AAP_ALIAS" text NOT NULL,
    "AAP_DELETE" timestamp without time zone,
    "URO_ID_URO_ID" bigint NOT NULL,
    "PLG_ID_PLG_ID" bigint NOT NULL,
    "MED_ID_MED_ID" bigint NOT NULL
);


ALTER TABLE public."T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP" OWNER TO echoes;

--
-- TOC entry 223 (class 1259 OID 172331)
-- Dependencies: 6
-- Name: T_ALERT_MESSAGE_DEFINITION_AMD; Type: TABLE; Schema: public; Owner: echoes; Tablespace: 
--

CREATE TABLE "T_ALERT_MESSAGE_DEFINITION_AMD" (
    version integer NOT NULL,
    "AMD_MESSAGE" text NOT NULL,
    "AMD_DELETE" timestamp without time zone,
    "AMD_IS_CUSTOM" boolean NOT NULL,
    "ALE_ID_ALE_ID" bigint NOT NULL,
    "URO_ID_URO_ID" bigint NOT NULL,
    "MED_ID_MED_ID" bigint NOT NULL
);


ALTER TABLE public."T_ALERT_MESSAGE_DEFINITION_AMD" OWNER TO echoes;


-- VIRER IVA_SLO de IVA


ALTER TABLE "T_MEDIA_VALUE_MEV" ADD COLUMN "MEV_IS_DEFAULT" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "T_USER_ROLE_URO" ADD COLUMN "URO_ORG_ORG_ID" bigint;

--
-- TOC entry 2439 (class 2606 OID 172330)
-- Dependencies: 222 222 222 222 2617
-- Name: T_ALERT_MESSAGE_ALIAS_ASSET_AAA_pkey; Type: CONSTRAINT; Schema: public; Owner: echoes; Tablespace: 
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_ASSET_AAA"
    ADD CONSTRAINT "T_ALERT_MESSAGE_ALIAS_ASSET_AAA_pkey" PRIMARY KEY ("URO_ID_URO_ID", "AST_ID_AST_ID", "MED_ID_MED_ID");


--
-- TOC entry 2449 (class 2606 OID 172376)
-- Dependencies: 229 229 229 229 229 229 229 229 2617
-- Name: T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI_pkey; Type: CONSTRAINT; Schema: public; Owner: echoes; Tablespace: 
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI"
    ADD CONSTRAINT "T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI_pkey" PRIMARY KEY ("URO_ID_URO_ID", "SEA_ID", "SRC_ID", "PLG_ID_PLG_ID", "INF_VALUE_NUM", "INU_ID_INU_ID", "MED_ID_MED_ID");


--
-- TOC entry 2451 (class 2606 OID 172384)
-- Dependencies: 230 230 230 230 230 230 230 230 230 2617
-- Name: T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC_pkey; Type: CONSTRAINT; Schema: public; Owner: echoes; Tablespace: 
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC"
    ADD CONSTRAINT "T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC_pkey" PRIMARY KEY ("URO_ID_URO_ID", "SEA_ID", "SRC_ID", "PLG_ID_PLG_ID", "INF_VALUE_NUM", "INU_ID_INU_ID", "ACR_ID_ACR_ID", "MED__ID_MED_ID");


--
-- TOC entry 2443 (class 2606 OID 172346)
-- Dependencies: 224 224 224 224 2617
-- Name: T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP_pkey; Type: CONSTRAINT; Schema: public; Owner: echoes; Tablespace: 
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP"
    ADD CONSTRAINT "T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP_pkey" PRIMARY KEY ("URO_ID_URO_ID", "PLG_ID_PLG_ID", "MED_ID_MED_ID");


--
-- TOC entry 2441 (class 2606 OID 172338)
-- Dependencies: 223 223 223 223 2617
-- Name: T_ALERT_MESSAGE_DEFINITION_AMD_pkey; Type: CONSTRAINT; Schema: public; Owner: echoes; Tablespace: 
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_DEFINITION_AMD"
    ADD CONSTRAINT "T_ALERT_MESSAGE_DEFINITION_AMD_pkey" PRIMARY KEY ("ALE_ID_ALE_ID", "URO_ID_URO_ID", "MED_ID_MED_ID");

--
-- TOC entry 2571 (class 2606 OID 172861)
-- Dependencies: 2460 222 240 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_ASSET_AAA_AST_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_ASSET_AAA"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_ASSET_AAA_AST_ID" FOREIGN KEY ("AST_ID_AST_ID") REFERENCES "T_ASSET_AST"("AST_ID");


--
-- TOC entry 2572 (class 2606 OID 172866)
-- Dependencies: 2462 242 222 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_ASSET_AAA_MED_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_ASSET_AAA"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_ASSET_AAA_MED_ID" FOREIGN KEY ("MED_ID_MED_ID") REFERENCES "T_MEDIA_MED"("MED_ID");


--
-- TOC entry 2570 (class 2606 OID 172856)
-- Dependencies: 258 222 2480 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_ASSET_AAA_URO_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_ASSET_AAA"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_ASSET_AAA_URO_ID" FOREIGN KEY ("URO_ID_URO_ID") REFERENCES "T_USER_ROLE_URO"("URO_ID");


--
-- TOC entry 2585 (class 2606 OID 172931)
-- Dependencies: 229 229 2386 176 176 176 176 229 176 229 229 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI_INF_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI_INF_ID" FOREIGN KEY ("SEA_ID", "SRC_ID", "PLG_ID_PLG_ID", "INF_VALUE_NUM", "INU_ID_INU_ID") REFERENCES "T_INFORMATION_INF"("SEA_ID", "SRC_ID", "PLG_ID_PLG_ID", "INF_VALUE_NUM", "INU_ID_INU_ID");


--
-- TOC entry 2586 (class 2606 OID 172936)
-- Dependencies: 2462 229 242 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI_MED_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI_MED_ID" FOREIGN KEY ("MED_ID_MED_ID") REFERENCES "T_MEDIA_MED"("MED_ID");


--
-- TOC entry 2584 (class 2606 OID 172926)
-- Dependencies: 229 2480 258 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI_URO_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_AAI_URO_ID" FOREIGN KEY ("URO_ID_URO_ID") REFERENCES "T_USER_ROLE_URO"("URO_ID");


--
-- TOC entry 2589 (class 2606 OID 172951)
-- Dependencies: 2392 182 230 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC_ACR_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC_ACR_ID" FOREIGN KEY ("ACR_ID_ACR_ID") REFERENCES "T_ALERT_CRITERIA_ACR"("ACR_ID");


--
-- TOC entry 2588 (class 2606 OID 172946)
-- Dependencies: 230 230 230 176 176 176 2386 230 230 176 176 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC_INF_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC_INF_ID" FOREIGN KEY ("SEA_ID", "SRC_ID", "PLG_ID_PLG_ID", "INF_VALUE_NUM", "INU_ID_INU_ID") REFERENCES "T_INFORMATION_INF"("SEA_ID", "SRC_ID", "PLG_ID_PLG_ID", "INF_VALUE_NUM", "INU_ID_INU_ID");


--
-- TOC entry 2590 (class 2606 OID 172956)
-- Dependencies: 242 2462 230 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC_MED__ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC_MED__ID" FOREIGN KEY ("MED__ID_MED_ID") REFERENCES "T_MEDIA_MED"("MED_ID");


--
-- TOC entry 2587 (class 2606 OID 172941)
-- Dependencies: 258 230 2480 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC_URO_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_INFORMATION_CRITERIA_AIC_URO_ID" FOREIGN KEY ("URO_ID_URO_ID") REFERENCES "T_USER_ROLE_URO"("URO_ID");


--
-- TOC entry 2578 (class 2606 OID 172896)
-- Dependencies: 224 2462 242 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP_MED_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP_MED_ID" FOREIGN KEY ("MED_ID_MED_ID") REFERENCES "T_MEDIA_MED"("MED_ID");


--
-- TOC entry 2577 (class 2606 OID 172891)
-- Dependencies: 2472 252 224 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP_PLG_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP_PLG_ID" FOREIGN KEY ("PLG_ID_PLG_ID") REFERENCES "T_PLUGIN_PLG"("PLG_ID");


--
-- TOC entry 2576 (class 2606 OID 172886)
-- Dependencies: 224 258 2480 2617
-- Name: fk_T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP_URO_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_ALIAS_PLUGIN_AAP_URO_ID" FOREIGN KEY ("URO_ID_URO_ID") REFERENCES "T_USER_ROLE_URO"("URO_ID");


--
-- TOC entry 2573 (class 2606 OID 172871)
-- Dependencies: 223 238 2458 2617
-- Name: fk_T_ALERT_MESSAGE_DEFINITION_AMD_ALE_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_DEFINITION_AMD"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_DEFINITION_AMD_ALE_ID" FOREIGN KEY ("ALE_ID_ALE_ID") REFERENCES "T_ALERT_ALE"("ALE_ID");


--
-- TOC entry 2575 (class 2606 OID 172881)
-- Dependencies: 242 2462 223 2617
-- Name: fk_T_ALERT_MESSAGE_DEFINITION_AMD_MED_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_DEFINITION_AMD"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_DEFINITION_AMD_MED_ID" FOREIGN KEY ("MED_ID_MED_ID") REFERENCES "T_MEDIA_MED"("MED_ID");


--
-- TOC entry 2574 (class 2606 OID 172876)
-- Dependencies: 2480 223 258 2617
-- Name: fk_T_ALERT_MESSAGE_DEFINITION_AMD_URO_ID; Type: FK CONSTRAINT; Schema: public; Owner: echoes
--

ALTER TABLE ONLY "T_ALERT_MESSAGE_DEFINITION_AMD"
    ADD CONSTRAINT "fk_T_ALERT_MESSAGE_DEFINITION_AMD_URO_ID" FOREIGN KEY ("URO_ID_URO_ID") REFERENCES "T_USER_ROLE_URO"("URO_ID");


ALTER TABLE ONLY "T_USER_ROLE_URO"
    ADD CONSTRAINT "fk_T_USER_ROLE_URO_URO_ORG" FOREIGN KEY ("URO_ORG_ORG_ID") REFERENCES "T_ORGANIZATION_ORG"("ORG_ID");



