ALTER TABLE "T_INFORMATION_VALUE_IVA" DROP COLUMN "IVA_SLH_SLH_ID";

ALTER TABLE "T_INFORMATION_VALUE_IVA"
ADD CONSTRAINT "fk_T_INFORMATION_VALUE_IVA_IVA_SLO" FOREIGN KEY ("IVA_SLO_SLO_ID")
      REFERENCES "T_SYSLOG_SLO" ("SLO_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "T_INFORMATION_HISTORICAL_VALUE_IHV" DROP COLUMN "IHV_SLH_SLH_ID";

ALTER TABLE "T_INFORMATION_HISTORICAL_VALUE_IHV"
ADD CONSTRAINT "fk_T_INFORMATION_VALUE_IHV_IHV_SLO" FOREIGN KEY ("IHV_SLO_SLO_ID")
      REFERENCES "T_SYSLOG_SLO" ("SLO_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE SET NULL;

DROP TRIGGER insert_slo ON "T_SYSLOG_SLO";

DROP FUNCTION trg_slo_slh();

DROP TABLE "T_SYSLOG_HISTORY_SLH";
