ALTER TABLE "T_MEDIA_VALUE_MEV" ADD COLUMN "MEV_TOKEN" text;

UPDATE "T_MEDIA_VALUE_MEV" SET "MEV_TOKEN" = (left(md5(random()::text), 25));

ALTER TABLE "T_MEDIA_VALUE_MEV" ALTER COLUMN "MEV_TOKEN" SET NOT NULL;

ALTER TABLE "T_MEDIA_VALUE_MEV" ADD COLUMN "MEV_IS_CONFIRMED" boolean DEFAULT FALSE;

